### ISSUE TITLE
Deprecation notice in `mb_strtolower` caused by Glide::index call

### ISSUE THREAD

**Issue by florianbrinkmann** [visuellverstehen/statamic-picturesque#11]
I noticed deprecation warnings that seem to originate in the way `Glide::index` is called. There the complete `Asset` object is passed as the `src` param, but `Glide::generateGlideUrl` expects a string. Here is the warning with stacktrace:

```bash
[12:05:02] LOG.warning: ErrorException: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /project/path/vendor/laravel/framework/src/Illuminate/Support/Str.php:590
Stack trace:
#0 /project/path/vendor/laravel/framework/src/Illuminate/Support/helpers.php(432): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Illuminate\Log\Logger))
#1 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(102): with(Object(Illuminate\Log\Logger), Object(Closure))
#2 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecationError('mb_strtolower()...', '/Users/vvfbri/p...', 590, 8192)
#3 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'mb_strtolower()...', '/Users/vvfbri/p...', 590)
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(8192, 'mb_strtolower()...', '/Users/vvfbri/p...', 590)
#5 /project/path/vendor/laravel/framework/src/Illuminate/Support/Str.php(590): mb_strtolower(NULL, 'UTF-8')
#6 /project/path/vendor/statamic/cms/src/Support/Str.php(314): Illuminate\Support\Str::lower(NULL)
#7 /project/path/vendor/statamic/cms/src/Imaging/ImageValidator.php(57): Statamic\Support\Str::__callStatic('lower', Array)
#8 /project/path/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Statamic\Imaging\ImageValidator->isValidExtension(NULL)
#9 /project/path/vendor/statamic/cms/src/Tags/Glide.php(344): Illuminate\Support\Facades\Facade::__callStatic('isValidExtensio...', Array)
#10 /project/path/vendor/statamic/cms/src/Tags/Glide.php(349): Statamic\Tags\Glide->isValidExtension('/de/img/asset/Y...')
#11 /project/path/vendor/statamic/cms/src/Tags/Glide.php(206): Statamic\Tags\Glide->useAbsoluteUrls('/de/img/asset/Y...')
#12 /project/path/vendor/statamic/cms/src/Tags/Glide.php(59): Statamic\Tags\Glide->generateGlideUrl(Object(Statamic\Assets\Asset))
#13 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Picturesque.php(251): Statamic\Tags\Glide->index()
#14 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Picturesque.php(361): VV\Picturesque\Picturesque->makeGlideUrl(Array)
#15 [internal function]: VV\Picturesque\Picturesque->VV\Picturesque\{closure}(Array, 2)
#16 /project/path/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#17 /project/path/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\Support\Arr::map(Array, Object(Closure))
#18 /project/path/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(1564): Illuminate\Support\Collection->map(Object(Closure))
#19 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Picturesque.php(359): Illuminate\Support\Collection->transform(Object(Closure))
#20 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Picturesque.php(308): VV\Picturesque\Picturesque->makeSrcset(Array, 'webp')
#21 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Picturesque.php(324): VV\Picturesque\Picturesque->makeSource(Array, 'webp', 'md')
#22 [internal function]: VV\Picturesque\Picturesque->VV\Picturesque\{closure}(768, 'md')
#23 /project/path/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#24 /project/path/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(777): Illuminate\Support\Arr::map(Array, Object(Closure))
#25 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Picturesque.php(322): Illuminate\Support\Collection->map(Object(Closure))
#26 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Picturesque.php(102): VV\Picturesque\Picturesque->makeSourcesForBreakpoints()
#27 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Tags/Picture.php(121): VV\Picturesque\Picturesque->generate()
#28 /project/path/vendor/visuellverstehen/statamic-picturesque/src/Tags/Picture.php(63): VV\Picturesque\Tags\Picture->output(Object(Statamic\Assets\Asset))
#29 [internal function]: VV\Picturesque\Tags\Picture->__call('image', Array)
#30 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func(Array)
#31 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\View\Antlers\Language\Runtime\NodeProcessor->reduce(Array)
#32 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\View\Antlers\Language\Runtime\NodeProcessor->render(Array)
#33 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\View\Antlers\Language\Runtime\RuntimeParser->renderText('{{ if type == '...', Array)
#34 /project/path/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\View\Antlers\Language\Runtime\RuntimeParser->parseView('/Users/vvfbri/p...', '{{ if type == '...', Array)
#35 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\View\Antlers\Engine->get('/Users/vvfbri/p...', Array)
#36 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#37 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#38 /project/path/vendor/statamic/cms/src/Tags/Partial.php(29): Illuminate\View\View->render()
#39 /project/path/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\Tags\Partial->render('media')
#40 /project/path/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\Tags\Partial->wildcard('media')
#41 [internal function]: Statamic\Tags\Tags->__call('media', Array)
#42 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func(Array)
#43 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(2324): Statamic\View\Antlers\Language\Runtime\NodeProcessor->reduce(Array)
#44 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\View\Antlers\Language\Runtime\NodeProcessor->reduce(Array)
#45 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\View\Antlers\Language\Runtime\NodeProcessor->render(Array)
#46 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\View\Antlers\Language\Runtime\RuntimeParser->renderText('<figure>\n    {{...', Array)
#47 /project/path/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\View\Antlers\Language\Runtime\RuntimeParser->parseView('/Users/vvfbri/p...', '<figure>\n    {{...', Array)
#48 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\View\Antlers\Engine->get('/Users/vvfbri/p...', Array)
#49 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#50 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#51 /project/path/vendor/statamic/cms/src/Tags/Partial.php(29): Illuminate\View\View->render()
#52 /project/path/vendor/statamic/cms/src/Tags/Partial.php(101): Statamic\Tags\Partial->render('sets/pagebuilde...')
#53 [internal function]: Statamic\Tags\Partial->ifExists()
#54 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func(Array)
#55 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(2324): Statamic\View\Antlers\Language\Runtime\NodeProcessor->reduce(Array)
#56 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\View\Antlers\Language\Runtime\NodeProcessor->reduce(Array)
#57 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\View\Antlers\Language\Runtime\NodeProcessor->render(Array)
#58 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\View\Antlers\Language\Runtime\RuntimeParser->renderText('{{ pagebuilder ...', Array)
#59 /project/path/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\View\Antlers\Language\Runtime\RuntimeParser->parseView('/Users/vvfbri/p...', '{{ pagebuilder ...', Array)
#60 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\View\Antlers\Engine->get('/Users/vvfbri/p...', Array)
#61 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#62 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#63 /project/path/vendor/statamic/cms/src/Tags/Partial.php(29): Illuminate\View\View->render()
#64 /project/path/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\Tags\Partial->render('pagebuilder')
#65 /project/path/vendor/statamic/cms/src/Tags/Tags.php(138): Statamic\Tags\Partial->wildcard('pagebuilder')
#66 [internal function]: Statamic\Tags\Tags->__call('pagebuilder', Array)
#67 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func(Array)
#68 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\View\Antlers\Language\Runtime\NodeProcessor->reduce(Array)
#69 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\View\Antlers\Language\Runtime\NodeProcessor->render(Array)
#70 /project/path/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\View\Antlers\Language\Runtime\RuntimeParser->renderText('{{ partial:text...', Array)
#71 /project/path/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\View\Antlers\Language\Runtime\RuntimeParser->parseView('/Users/vvfbri/p...', '{{ partial:text...', Array)
#72 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(207): Statamic\View\Antlers\Engine->get('/Users/vvfbri/p...', Array)
#73 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#74 /project/path/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#75 /project/path/vendor/statamic/cms/src/View/View.php(100): Illuminate\View\View->render()
#76 /project/path/vendor/statamic/cms/src/Http/Responses/DataResponse.php(146): Statamic\View\View->render()
#77 /project/path/vendor/statamic/cms/src/Http/Responses/DataResponse.php(42): Statamic\Http\Responses\DataResponse->contents()
#78 /project/path/vendor/statamic/cms/src/Structures/Page.php(384): Statamic\Http\Responses\DataResponse->toResponse(Object(Illuminate\Http\Request))
#79 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Router.php(900): Statamic\Structures\Page->toResponse(Object(Illuminate\Http\Request))
#80 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#81 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#82 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#83 /project/path/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /project/path/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#86 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\AuthGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#87 /project/path/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#88 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\AddViewPaths->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 /project/path/vendor/statamic/cms/src/Http/Middleware/Localize.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#91 /project/path/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\HandleToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#93 /project/path/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#94 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\StacheLock->handle(Object(Illuminate\Http\Request), Object(Closure))
#95 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#96 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#97 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#98 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#99 /project/path/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#100 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#101 /project/path/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 /project/path/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#103 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#104 /project/path/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#105 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#106 /project/path/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#107 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#108 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#109 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#110 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#111 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#112 /project/path/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#113 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#114 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#115 /project/path/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#116 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\StopImpersonating->handle(Object(Illuminate\Http\Request), Object(Closure))
#117 /project/path/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#118 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\DisableFloc->handle(Object(Illuminate\Http\Request), Object(Closure))
#119 /project/path/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#120 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\CheckMultisite->handle(Object(Illuminate\Http\Request), Object(Closure))
#121 /project/path/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#122 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\CheckComposerJsonScripts->handle(Object(Illuminate\Http\Request), Object(Closure))
#123 /project/path/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#124 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\Http\Middleware\PoweredByHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#125 /project/path/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#126 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#127 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#128 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#129 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#130 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#131 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#132 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#133 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#134 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#135 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#136 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#137 /project/path/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#138 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#139 /project/path/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#140 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#141 /project/path/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#142 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#143 /project/path/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#144 /project/path/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#145 /Users/vvfbri/.composer/vendor/laravel/valet/server.php(110): require('/Users/vvfbri/p...')
#146 {main}

```

**Comment by simonolog** [comment]
@florianbrinkmann Can you see if that still exists? As we're only extending Statamics `glide` tag and use all of their handling, I don't really see an easy way to do anything about that. If this is still flooding your logs, maybe it'd be better to open an issue in statamic/cms.

**Comment by florianbrinkmann** [comment]
Not sure which project it was, let’s close it for now :)
